import type { Study } from '@/types';

export function getSeedData(): Study[] {
  return [
    {
      id: 'seed_1',
      title: 'Estudio de Inteligencia Política Digital — Metepec, Estado de México',
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      archetype: 'Constructor',
      archetypeUncertainty: 'Media',
      positivePoints: [
        'Experiencia comprobada en gestión municipal y resultados tangibles en infraestructura urbana',
        'Capacidad de diálogo con diferentes sectores políticos y sociales del municipio',
        'Compromiso histórico con programas de desarrollo económico local',
      ],
      positivePointsUncertainty: 'Baja',
      negativePoints: [
        'Vinculación con escándalos de corrupción en administraciones anteriores',
        'Falta de propuestas claras en materia de seguridad pública',
        'Débil presencia en redes sociales y plataformas digitales',
      ],
      negativePointsUncertainty: 'Media',
      candidates: [
        {
          id: 'c1',
          name: 'María Teresa González',
          party: 'Morena',
          adjectives: ['Experiencia', 'Liderazgo', 'Compromiso', 'Trabajo'],
          digitalSignal: 'Predomina narrativa de continuidad de proyectos y crítica a gestiones anteriores',
        },
        {
          id: 'c2',
          name: 'Roberto Martínez Silva',
          party: 'PRI-PAN-PRD (Alianza)',
          adjectives: ['Renovación', 'Honestidad', 'Cambio', 'Resultados'],
          digitalSignal: 'Enfoque en transparencia y combate a corrupción, con mensajes anti-establishment',
        },
        {
          id: 'c3',
          name: 'Ana Lucía Ramírez',
          party: 'Movimiento Ciudadano',
          adjectives: ['Juventud', 'Innovación', 'Inclusión', 'Tecnología'],
          digitalSignal: 'Estrategia digital fuerte con propuestas de gobierno electrónico y participación ciudadana',
        },
        {
          id: 'c4',
          name: 'Wblester Santiago Pineda',
          party: 'Independiente',
          adjectives: ['Autonomía', 'Cercanía', 'Experiencia', 'Gestión'],
          digitalSignal: 'Comunicación directa con ciudadanos, énfasis en independencia de partidos tradicionales',
        },
      ],
      candidatesUncertainty: 'Baja',
      digitalUniverse: 120000,
      digitalUniverseUncertainty: 'Media',
      blockA: [
        {
          id: 'ba1',
          party: 'Morena',
          duro: 25,
          enojado: 8,
          critico: 12,
          oportunista: 5,
        },
        {
          id: 'ba2',
          party: 'PRI-PAN-PRD',
          duro: 18,
          enojado: 15,
          critico: 10,
          oportunista: 7,
        },
        {
          id: 'ba3',
          party: 'MC',
          duro: 8,
          enojado: 5,
          critico: 6,
          oportunista: 11,
        },
      ],
      blockAUncertainty: 'Alta',
      blockB: [
        {
          id: 'bb1',
          segment: 'Jóvenes urbanos',
          description: 'Millennials y Gen Z con acceso digital constante',
          size: 35,
        },
        {
          id: 'bb2',
          segment: 'Clase media tradicional',
          description: 'Familias establecidas con preocupaciones económicas',
          size: 45,
        },
        {
          id: 'bb3',
          segment: 'Adultos mayores',
          description: 'Población senior con baja participación digital',
          size: 20,
        },
      ],
      blockBUncertainty: 'Media',
    },
    {
      id: 'seed_2',
      title: 'Análisis Electoral — Toluca Centro',
      createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      archetype: 'Reformador',
      archetypeUncertainty: 'Baja',
      positivePoints: [
        'Propuestas innovadoras en movilidad urbana y transporte público',
        'Alto nivel de aprobación entre jóvenes profesionistas',
      ],
      positivePointsUncertainty: 'Baja',
      negativePoints: [
        'Falta de experiencia en cargos públicos de alto nivel',
        'Presupuesto limitado para campaña electoral',
      ],
      negativePointsUncertainty: 'Alta',
      candidates: [
        {
          id: 'c1',
          name: 'Carlos Hernández',
          party: 'Morena',
          adjectives: ['Continuidad', 'Estabilidad', 'Experiencia', 'Confianza'],
          digitalSignal: 'Mensajes centrados en logros de la 4T y programas sociales',
        },
        {
          id: 'c2',
          name: 'Patricia Ruiz',
          party: 'PAN',
          adjectives: ['Cambio', 'Eficiencia', 'Transparencia', 'Orden'],
          digitalSignal: 'Crítica a gobierno actual con propuestas de mejora administrativa',
        },
        {
          id: 'c3',
          name: 'Miguel Ángel Torres',
          party: 'PRD',
          adjectives: ['Justicia', 'Social', 'Tradición', 'Lucha'],
          digitalSignal: 'Retórica de izquierda clásica con énfasis en derechos laborales',
        },
        {
          id: 'c4',
          name: 'Wblester Santiago Pineda',
          party: 'Independiente',
          adjectives: ['Independencia', 'Pragmatismo', 'Resultados', 'Cercanía'],
          digitalSignal: 'Posicionamiento equidistante de todos los partidos políticos',
        },
      ],
      candidatesUncertainty: 'Media',
      digitalUniverse: 95000,
      digitalUniverseUncertainty: 'Baja',
      blockA: [
        {
          id: 'ba1',
          party: 'Morena',
          duro: 22,
          enojado: 6,
          critico: 9,
          oportunista: 4,
        },
        {
          id: 'ba2',
          party: 'PAN',
          duro: 15,
          enojado: 12,
          critico: 8,
          oportunista: 6,
        },
      ],
      blockAUncertainty: 'Media',
      blockB: [
        {
          id: 'bb1',
          segment: 'Comerciantes del centro',
          description: 'Pequeños y medianos empresarios del primer cuadro',
          size: 18,
        },
        {
          id: 'bb2',
          segment: 'Estudiantes universitarios',
          description: 'Población estudiantil de instituciones públicas y privadas',
          size: 28,
        },
      ],
      blockBUncertainty: 'Alta',
    },
  ];
}
